server:
  port: 8081

spring:
  application:
    name: Meeting_Notes_Summariser

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres

  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    openai:
      api-key: ${GROQ_API_KEY}
      base-url: ${GROQ_BASE_URL}
      chat:
        model: ${GROQ_MODEL}
        temperature: 0.7

logging:
  level:
    root: INFO
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG